Repository edysaul20000/PC4-Proyecto-14, pull requests merged in 2025-06, with the labels that each got.

#3 merge[#1]: Feature/microservice-basic a develop
  Services/microservice/app/main.py
  Services/microservice/requirements.txt
Labels: Importante, Documentation, Sprint-1

#7 merge[#5]: Feature/microservice-mock a develop
  .env
  Services/mock/mock_app/mock.py
  Services/mock/requirements.txt
Labels: Importante, Sprint-1

#8 merge[#6]: Feature/mock-docker a develop
  Services/mock/Dockerfile
Labels: Importante, Docker, Sprint-1

#17 chore[#15]: tag v1.0.0 y merge release branch a main
  .env
  .gitignore
  README.md
  Services/hooks/pre-commit
  Services/microservice/Dockerfile
  Services/microservice/app/main.py
  Services/microservice/requirements.txt
  Services/mock/Dockerfile
  Services/mock/mock_app/mock.py
  Services/mock/requirements.txt
  docker-compose.yaml
  services/hooks/pre-commit
  services/microservice/Dockerfile
  services/microservice/app/main.py
  services/microservice/requirements.txt
  services/mock/Dockerfile
  services/mock/mock_app/mock.py
  services/mock/requirements.txt
  test_env_builder.py
Labels: Importante, Documentation, Sprint-1

#19 merge[#16]: Feature/answer-mock a develop
  pytest.ini
  services/microservice/app/main.py
  services/microservice/tests/test_integration.py
  services/mock/mock_app/mock.py
Labels: Importante, Sprint-2, Test

#24 chore[#23]: tag v2.0.0 y merge release/sprint2 branch a main
  README.md
  pytest.ini
  services/microservice/app/main.py
  services/microservice/tests/test_integration.py
  services/mock/mock_app/mock.py
Labels: Importante, Documentation, Sprint-2

#29 merge[#25]: Feature/prueba-contrato a develop
  services/microservice/tests/contract_response_schema.json
  services/microservice/tests/test_contracts.py
Labels: Importante

#31 chore[#30]: tag v3.0.0 y merge release/sprint3 branch a main
  README.md
  scenarios/error_mock.yaml
  scenarios/success_simple.yaml
  scenarios/success_with_delay.yaml
  services/microservice/tests/contract_response_schema.json
  services/microservice/tests/test_contracts.py
  test_env_builder.py
Labels: Importante, Documentation, Sprint-3
